# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: ringal
version: '0.0.0'
github: "eschnett/ringal"
license: MIT
author: "Erik Schnetter"
maintainer: "Erik Schnetter"
# synopsis: A new Haskell package.
# description: ringal is a new Haskell package.
# category: Other

extra-source-files:
  - CHANGELOG.md
  - LICENSE.md
  - package.yaml
  - README.md
  - stack.yaml

ghc-options:
  - -foptimal-applicative-do
  - -funbox-strict-fields
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wno-unused-matches

default-extensions:
  # This is the set of default extensions supported by Ormolu
  # <https://github.com/tweag/ormolu>
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DerivingStrategies
  - DerivingVia
  - EmptyCase
  - EmptyDataDecls
  - ExistentialQuantification
  - ExplicitForAll
  - ExplicitNamespaces
  - ExtendedDefaultRules
  - FlexibleContexts
  - FlexibleInstances
  - ForeignFunctionInterface
  - FunctionalDependencies
  - GADTSyntax
  - GADTs
  - GeneralizedNewtypeDeriving
  - HexFloatLiterals
  - ImplicitParams
  - IncoherentInstances
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NPlusKPatterns
  - NamedFieldPuns
  - NamedWildCards
  # - NegativeLiterals   [breaks some subtractions]
  - NumericUnderscores
  - OverloadedLabels
  # - OverloadedLists   [requires type annotations on lists]
  - OverloadedStrings
  - PackageImports
  - PatternGuards
  - PolyKinds
  - QuantifiedConstraints
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - RecursiveDo
  - RoleAnnotations
  - ScopedTypeVariables
  - StandaloneDeriving
  - StarIsType
  - StaticPointers
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeInType
  - TypeOperators
  - UndecidableInstances
  - UndecidableSuperClasses
  # We like these extensions as well
  - ApplicativeDo
  - BlockArguments
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - ParallelListComp
  - PatternSynonyms
  - TypeSynonymInstances
  - UnicodeSyntax
  # We also like these extensions, although they might be controversial
  - AllowAmbiguousTypes
  - MonadComprehensions

library:
  dependencies:
    - QuickCheck
    - base
    - these
  source-dirs: src

executables:
  ringal:
    source-dirs: app
    main: Main.hs
    dependencies:
      - base
      - ringal
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

benchmarks:
  ringal-benchmarks:
    source-dirs: bench
    main: Main.hs
    dependencies:
      - base
      - criterion
      - ringal
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

tests:
  ringal-test-suite:
    source-dirs: test
    main: Main.hs
    dependencies:
      - QuickCheck
      - base
      - quickcheck-instances
      - tasty
      - tasty-discover
      - tasty-hspec
      - tasty-quickcheck
      - ringal
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
